version: '3'

services:

  app:
    build: 
      context: node
    container_name: app
    networks: 
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - proxy

  # db:
  #   image: mysql:5.7
  #   command: --innodb-use-native-aio=0
  #   container_name: db
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=nodedb
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_USER=root
  #   networks:
  #     - node-network

  proxy:
    build:
      context:  nginx
    container_name: proxy
    networks:
    - node-network
    volumes:
      - ./nginx:/var/www
    tty: true
    ports: 
      - "8080:80"
    # depends_on:
    #   - db
    
networks:
  node-network:
    driver: bridge